# Copyright (c) 2021-2022 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Encoders (Uncomment these two line to add support to your firmware)
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# RGB Underglow (Uncomment these two lines to add support to your firmware)
# RGB quickly drains battery power
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

# Boost the Bluetooth signal only if having connection issues
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable NKRO
# CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y

# Enable 12KRO
CONFIG_ZMK_HID_REPORT_TYPE_HKRO=y
CONFIG_ZMK_HID_KEYBOARD_REPORT_SIZE=12

# Battery reporting
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Sane Debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=8
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=8

# Mouse key emulation
CONFIG_ZMK_POINTING=y

# Enable Deep sleep after 30 min
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
